const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "anpp",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/9sXOKpU.jpeg",
"https://i.imgur.com/l9N9GN5.jpeg",
"https://i.imgur.com/rhKq4bQ.jpeg",
"https://i.imgur.com/rUtuuYx.jpeg",
"https://i.imgur.com/m8dtkMv.jpeg",
"https://i.imgur.com/Bi7j8GD.jpeg",
"https://i.imgur.com/bcopv5X.jpeg",
"https://i.imgur.com/RRZUa8V.jpeg",
"https://i.imgur.com/qbzjUDt.jpeg",
"https://i.imgur.com/I3L7xio.jpeg",
"https://i.imgur.com/fadENfE.jpeg",
"https://i.imgur.com/Y84EiBd.jpeg",
"https://i.imgur.com/A5iU5xz.jpeg",
"https://i.imgur.com/MaKhAZ7.jpeg",
"https://i.imgur.com/RuL6Jw5.jpeg",
"https://i.imgur.com/kORKAtP.jpeg",
"https://i.imgur.com/7dexoqO.jpeg",
"https://i.imgur.com/6Xecpsu.jpeg",
"https://i.imgur.com/pghMjbB.jpeg",
"https://i.imgur.com/hq0WeQX.jpeg",
"https://i.imgur.com/msxj7rh.jpeg",
"https://i.imgur.com/5NjvHdy.jpeg",
"https://i.imgur.com/aGNPB31.jpeg",
"https://i.imgur.com/wMBraMh.jpeg",
"https://i.imgur.com/ZgxcoTs.jpeg",
"https://i.imgur.com/2yG7mFk.jpeg",
"https://i.imgur.com/vOOlyKo.jpeg",
"https://i.imgur.com/1NFKndu.jpeg",
"https://i.imgur.com/QFRYmZe.jpeg",
"https://i.imgur.com/wfixJuj.jpeg",
"https://i.imgur.com/o3P7KDD.jpeg",
"https://i.imgur.com/w38So5e.jpeg",
"https://i.imgur.com/SfdJped.jpeg",
"https://i.imgur.com/JzpScdB.jpeg",
"https://i.imgur.com/o5huu0t.jpeg",
"https://i.imgur.com/HqiLuYP.jpeg",
"https://i.imgur.com/QwS2QhQ.jpeg",
"https://i.imgur.com/Q2VJofw.jpeg",
"https://i.imgur.com/ryNENAD.jpeg",
"https://i.imgur.com/kZ2jnvr.jpeg",
"https://i.imgur.com/5xqJP4H.jpeg",
"https://i.imgur.com/8rP6Px8.jpeg",
"https://i.imgur.com/h8QgMDU.jpeg",
"https://i.imgur.com/yabRwB0.jpeg",
"https://i.imgur.com/xAFBnuJ.jpeg",
"https://i.imgur.com/NjTsMgZ.jpeg",
"https://i.imgur.com/013PciY.jpeg",
"https://i.imgur.com/wkpTdb1.jpeg",
"https://i.imgur.com/y4NTgBc.jpeg",
"https://i.imgur.com/pstp04s.jpeg",
"https://i.imgur.com/Lw7epHa.jpeg",
"https://i.imgur.com/rJvY7CU.jpeg",
"https://i.imgur.com/4sbs0dN.jpeg",
"https://i.imgur.com/dKQQfvR.jpeg",
"https://i.imgur.com/ZRXuTNq.jpeg",
"https://i.imgur.com/FnvVoGx.jpeg",
"https://i.imgur.com/DQtlfcA.jpeg",
"https://i.imgur.com/V7Vbd14.jpeg",
"https://i.imgur.com/OHVquhi.jpeg",
"https://i.imgur.com/ipdipbb.jpeg",
"https://i.imgur.com/wNQiToO.jpeg",
"https://i.imgur.com/pa8Q39T.jpeg",
"https://i.imgur.com/DhwuC8O.jpeg",
"https://i.imgur.com/hdyzRFK.jpeg",
"https://i.imgur.com/aoF5cdK.jpeg",
"https://i.imgur.com/42oF2xX.jpeg",
"https://i.imgur.com/BiTpXEv.jpeg",
"https://i.imgur.com/NjVhPrj.jpeg",
"https://i.imgur.com/NCep8By.jpeg",
"https://i.imgur.com/Ye25yf1.jpeg",
"https://i.imgur.com/S56LnGV.jpeg",
"https://i.imgur.com/rVhgsLm.jpeg",
"https://i.imgur.com/YzyP9Lo.jpeg",
"https://i.imgur.com/qXyt37g.jpeg",
"https://i.imgur.com/AsIbTAw.jpeg",
"https://i.imgur.com/18uVcRD.jpeg",
"https://i.imgur.com/hYBHgus.jpeg",
"https://i.imgur.com/hqjjhci.jpeg",
"https://i.imgur.com/PJPBzfp.jpeg",
"https://i.imgur.com/3ZKQztT.jpeg",
"https://i.imgur.com/KlH5oY4.jpeg",
"https://i.imgur.com/OLIrhF2.jpeg",
"https://i.imgur.com/RMvgMbk.jpeg",
"https://i.imgur.com/jL9ufws.jpeg",
"https://i.imgur.com/7qq7qU2.jpeg",
"https://i.imgur.com/cK5dpzk.jpeg",
"https://i.imgur.com/IAMy6oT.jpeg",
"https://i.imgur.com/R9D2K6j.jpeg",
"https://i.imgur.com/EPjxVS0.jpeg",
"https://i.imgur.com/cnH5TP0.jpeg",
"https://i.imgur.com/k2SVkK8.jpeg",
"https://i.imgur.com/zzgAy2L.jpeg",
"https://i.imgur.com/a6Rj1gs.jpeg",
"https://i.imgur.com/GTae0Wl.jpeg",
"https://i.imgur.com/RyveWzW.jpeg",
"https://i.imgur.com/7uYE5aI.jpeg",
"https://i.imgur.com/lMy2gqi.jpeg",
"https://i.imgur.com/YFL4CQD.jpeg",
"https://i.imgur.com/FCAOYBe.jpeg",
"https://i.imgur.com/n39aU2z.jpeg",
"https://i.imgur.com/K9hBHbq.jpeg",
"https://i.imgur.com/CbPZwIX.jpeg",
"https://i.imgur.com/FzBywWc.jpeg",
"https://i.imgur.com/w9ApNYt.jpeg",
"https://i.imgur.com/L7xCfgF.jpeg",
"https://i.imgur.com/N12GdAM.jpeg",
"https://i.imgur.com/TXQtvml.jpeg",
"https://i.imgur.com/qgtHCoX.jpeg",
"https://i.imgur.com/Wea1LIb.jpeg",
"https://i.imgur.com/u91G4Z4.jpeg",
"https://i.imgur.com/YksP9d8.jpeg",
"https://i.imgur.com/mWa7bjQ.jpeg",
"https://i.imgur.com/bLekzRk.jpeg",
"https://i.imgur.com/1csXTgD.jpeg",
"https://i.imgur.com/lWJOC4s.jpeg",
"https://i.imgur.com/DWTS1DS.jpeg",
"https://i.imgur.com/pIm0E8M.jpeg",
"https://i.imgur.com/lpdBwTI.jpeg",
"https://i.imgur.com/TF4ygBx.jpeg",
"https://i.imgur.com/xKCIR6b.jpeg",
"https://i.imgur.com/iBNBKOT.jpeg",
"https://i.imgur.com/bAZa3yX.jpeg",
"https://i.imgur.com/YP11cFd.jpeg",
"https://i.imgur.com/3ikKJz6.jpeg",
"https://i.imgur.com/ZstT6TM.jpeg",
"https://i.imgur.com/cO6wQbi.jpeg",
"https://i.imgur.com/kVFLmcp.jpeg",
"https://i.imgur.com/YQHcKa3.jpeg",
"https://i.imgur.com/JLpwJlc.jpeg",
"https://i.imgur.com/MBBGHw9.jpeg",
"https://i.imgur.com/u9iPcOV.jpeg",
"https://i.imgur.com/I9iKu57.jpeg",
"https://i.imgur.com/8ETWIJu.jpeg",
"https://i.imgur.com/XuU9MHn.jpeg",
"https://i.imgur.com/vKDphPR.jpeg",
"https://i.imgur.com/muRPthN.jpeg",
"https://i.imgur.com/sp9254B.jpeg",
"https://i.imgur.com/ZlimLeQ.jpeg",
"https://i.imgur.com/1kykPkv.jpeg",
"https://i.imgur.com/2W5t74Y.jpeg",
"https://i.imgur.com/qdyyc4s.jpeg",
"https://i.imgur.com/JMq1GGQ.jpeg",
"https://i.imgur.com/dI2uMXV.jpeg",
"https://i.imgur.com/FpyZ4nj.jpeg",
"https://i.imgur.com/ncMmuD1.jpeg",
"https://i.imgur.com/4jpHYwP.jpeg",
"https://i.imgur.com/oxPM4gW.jpeg",
"https://i.imgur.com/XJb8KQa.jpeg",
"https://i.imgur.com/E9ph2Ar.jpeg"

];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "HOT anime pp",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
