const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "anppv2",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/OjUpaOO.jpeg",
"https://i.imgur.com/u7WXhN1.jpeg",
"https://i.imgur.com/ybkWFOW.jpeg",
"https://i.imgur.com/KhhLd3G.jpeg",
"https://i.imgur.com/1KIzqmf.jpeg",
"https://i.imgur.com/c6sCQYb.jpeg",
"https://i.imgur.com/dJsN2kw.jpeg",
"https://i.imgur.com/MT6k21W.jpeg",
"https://i.imgur.com/HcoklhO.jpeg",
"https://i.imgur.com/7h1yOSl.jpeg",
"https://i.imgur.com/iz9JQkv.jpeg",
"https://i.imgur.com/SXLuq8t.jpeg",
"https://i.imgur.com/aT5SyEi.jpeg",
"https://i.imgur.com/ApBF5Dy.jpeg",
"https://i.imgur.com/hrusj5N.jpeg",
"https://i.imgur.com/OEDTrR4.jpeg",
"https://i.imgur.com/q9w2h0g.jpeg",
"https://i.imgur.com/C6k5RKd.jpeg",
"https://i.imgur.com/C3bUFXf.jpeg",
"https://i.imgur.com/e6htHMH.jpeg",
"https://i.imgur.com/BOOXvnv.jpeg",
"https://i.imgur.com/Q10nwsg.jpeg",
"https://i.imgur.com/GCjcs8w.jpeg",
"https://i.imgur.com/vllDumc.jpeg",
"https://i.imgur.com/PijV174.jpeg",
"https://i.imgur.com/GUd9cXx.jpeg",
"https://i.imgur.com/sAhICyN.jpeg",
"https://i.imgur.com/A3teS0u.jpeg",
"https://i.imgur.com/9zVl7kq.jpeg",
"https://i.imgur.com/cbSFpsD.jpeg",
"https://i.imgur.com/Ey4D0ay.jpeg",
"https://i.imgur.com/XgQxlWu.jpeg",
"https://i.imgur.com/GiVGwws.jpeg",
"https://i.imgur.com/InnhWL2.jpeg",
"https://i.imgur.com/kD2yp4r.jpeg",
"https://i.imgur.com/fig1LXK.jpeg",
"https://i.imgur.com/eYqKT3C.jpeg",
"https://i.imgur.com/vAvKzDu.jpeg",
"https://i.imgur.com/BS9fgaj.jpeg",
"https://i.imgur.com/yIcte7a.jpeg",
"https://i.imgur.com/JDPspGu.jpeg",
"https://i.imgur.com/O22kdrU.jpeg",
"https://i.imgur.com/jocEHx2.jpeg",
"https://i.imgur.com/g50news.jpeg",
"https://i.imgur.com/hBUqbZd.jpeg",
"https://i.imgur.com/diHmbI1.jpeg",
"https://i.imgur.com/ZIhtSiC.jpeg",
"https://i.imgur.com/RKKlttX.jpeg",
"https://i.imgur.com/ek2lWsD.jpeg",
"https://i.imgur.com/ASEd9dP.jpeg",
"https://i.imgur.com/vpAf9dZ.jpeg",
"https://i.imgur.com/hojGXUJ.jpeg",
"https://i.imgur.com/GeJ37Px.jpeg",
"https://i.imgur.com/IDwvKL5.jpeg",
"https://i.imgur.com/3ItaVYz.jpeg",
"https://i.imgur.com/GIB0czd.jpeg",
"https://i.imgur.com/9xjbUAk.jpeg",
"https://i.imgur.com/5UeJHdT.jpeg",
"https://i.imgur.com/BZswHPW.jpeg",
"https://i.imgur.com/dr0Pesy.jpeg",
"https://i.imgur.com/6eXpv9D.jpeg",
"https://i.imgur.com/ubNw1RC.jpeg",
"https://i.imgur.com/tle9cNI.jpeg",
"https://i.imgur.com/8RB8hBd.jpeg",
"https://i.imgur.com/at6Knxz.jpeg",
"https://i.imgur.com/KNUzIQf.jpeg",
"https://i.imgur.com/5zfo6eC.jpeg",
"https://i.imgur.com/AviFHhr.jpeg",
"https://i.imgur.com/gnm4tk8.jpeg",
"https://i.imgur.com/99MxQMQ.jpeg",
"https://i.imgur.com/oZGtpBx.jpeg",
"https://i.imgur.com/UgkXfCq.jpeg",
"https://i.imgur.com/Op0QNda.jpeg",
"https://i.imgur.com/SMjHMbY.jpeg",
"https://i.imgur.com/w1kKgfV.jpeg",
"https://i.imgur.com/cFVzOAU.jpeg",
"https://i.imgur.com/eWJ34s2.jpeg",
"https://i.imgur.com/xYA0pEx.jpeg",
"https://i.imgur.com/woRnp6J.jpeg",
"https://i.imgur.com/4hC4TNY.jpeg",
"https://i.imgur.com/xz2TLMA.jpeg",
"https://i.imgur.com/eXNjyQe.jpeg",
"https://i.imgur.com/In2FOkS.jpeg",
"https://i.imgur.com/urvBpbA.jpeg",
"https://i.imgur.com/cC0eX4N.jpeg",
"https://i.imgur.com/2OQvgvO.jpeg",
"https://i.imgur.com/LEXxy0n.jpeg",
"https://i.imgur.com/i39Df2F.jpeg",
"https://i.imgur.com/iIhepCl.jpeg",
"https://i.imgur.com/UTxzyHD.jpeg",
"https://i.imgur.com/gyiat27.jpeg",
"https://i.imgur.com/8qEfhUx.jpeg",
"https://i.imgur.com/1Jgcxxo.jpeg",
"https://i.imgur.com/84f3k5a.jpeg",
"https://i.imgur.com/88Kh0QX.jpeg",
"https://i.imgur.com/XlHTJqE.jpeg",
"https://i.imgur.com/GCeaOnU.jpeg",
"https://i.imgur.com/dfUhHol.jpeg",
"https://i.imgur.com/C4dSoWM.jpeg",
"https://i.imgur.com/MGeyp9m.jpeg",
"https://i.imgur.com/5QyPARS.jpeg",
"https://i.imgur.com/8Ech7Ni.jpeg",
"https://i.imgur.com/xce8Mqg.jpeg",
"https://i.imgur.com/XbTC5G0.jpeg",
"https://i.imgur.com/vHVGm74.jpeg",
"https://i.imgur.com/uhsxxIk.jpeg",
"https://i.imgur.com/o9J1q8f.jpeg",
"https://i.imgur.com/r8A1pk1.jpeg",
"https://i.imgur.com/o2U23Xs.jpeg",
"https://i.imgur.com/U7Ctxse.jpeg",
"https://i.imgur.com/U7Ci9GF.jpeg",
"https://i.imgur.com/mvWhB2c.jpeg",
"https://i.imgur.com/KB4dokY.jpeg",
"https://i.imgur.com/PjSrG8L.jpeg",
"https://i.imgur.com/Yh4YsNd.jpeg",
"https://i.imgur.com/rrcORoC.jpeg",
"https://i.imgur.com/7E9vZYn.jpeg",
"https://i.imgur.com/HJwAOUa.jpeg",
"https://i.imgur.com/dWK8HYL.jpeg",
"https://i.imgur.com/gdeuN8t.jpeg",
"https://i.imgur.com/Iy8Odvy.jpeg",
"https://i.imgur.com/ugsgxeU.jpeg",
"https://i.imgur.com/8avtKBi.jpeg",
"https://i.imgur.com/U8jlNza.jpeg",
"https://i.imgur.com/WLZjU5X.jpeg",
"https://i.imgur.com/IHT0rsL.jpeg",
"https://i.imgur.com/55LO27j.jpeg",
"https://i.imgur.com/motKYy5.jpeg",
"https://i.imgur.com/7LTPp0W.jpeg",
"https://i.imgur.com/XHIQU7U.jpeg",
"https://i.imgur.com/zRnmDTA.jpeg",
"https://i.imgur.com/NK9iqza.jpeg",
"https://i.imgur.com/Zh8hXw3.jpeg",
"https://i.imgur.com/uPFnSVe.jpeg",
"https://i.imgur.com/iNVtPJm.jpeg",
"https://i.imgur.com/IDtG5Wj.jpeg",
"https://i.imgur.com/d9D9H0r.jpeg",
"https://i.imgur.com/fj6sk9U.jpeg",
"https://i.imgur.com/iasFfza.jpeg",
"https://i.imgur.com/hze6Ove.jpeg",
"https://i.imgur.com/ZGbBt8p.jpeg",

];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "HOT anime pp v2 🥳",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
