const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "banarx",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/OnKpqzT.jpeg",
"https://i.imgur.com/06UOjIf.jpeg",
"https://i.imgur.com/mmdDBKc.jpeg",
"https://i.imgur.com/iErDfBr.jpeg",
"https://i.imgur.com/pSItJ3W.jpeg",
"https://i.imgur.com/CEZcfgx.jpeg",
"https://i.imgur.com/xaTMhY7.jpeg",
"https://i.imgur.com/TueSRG8.jpeg",
"https://i.imgur.com/crbYK0S.jpeg",
"https://i.imgur.com/jesx1KT.jpeg",
"https://i.imgur.com/GbPntYQ.jpeg",
"https://i.imgur.com/6zDrl8z.jpeg",
"https://i.imgur.com/Ns3AmXE.jpeg",
"https://i.imgur.com/jf3OcCa.jpeg",
"https://i.imgur.com/Jc6S7fV.jpeg",
"https://i.imgur.com/56kxnUh.jpeg",
"https://i.imgur.com/IfUjoK4.jpeg",
"https://i.imgur.com/Omr6f9R.jpeg",
"https://i.imgur.com/6V3gzFn.jpeg",
"https://i.imgur.com/nrW4t0X.jpeg",
"https://i.imgur.com/3UZsB9X.jpeg",
"https://i.imgur.com/4j27fPQ.jpeg",
"https://i.imgur.com/sCWMUx4.jpeg",
"https://i.imgur.com/YcBhFvw.jpeg",
"https://i.imgur.com/KJfsslz.jpeg",
"https://i.imgur.com/NHPqUDt.jpeg",
"https://i.imgur.com/0Y8MRNm.jpeg",
"https://i.imgur.com/zbibnLw.jpeg",
"https://i.imgur.com/QbeZHO7.jpeg",
"https://i.imgur.com/F9H360X.jpeg",
"https://i.imgur.com/IsPV93J.jpeg",
"https://i.imgur.com/27pIWoI.jpeg",
"https://i.imgur.com/0lvQ4CU.jpeg",
"https://i.imgur.com/EexrIcF.jpeg",
"https://i.imgur.com/zQ7ZNC3.jpeg",
"https://i.imgur.com/UW8tlFR.jpeg",
"https://i.imgur.com/VJxZcau.jpeg",
"https://i.imgur.com/XNVclHz.jpeg",
"https://i.imgur.com/6GteVmS.jpeg",
"https://i.imgur.com/vnU2rGA.jpeg",
"https://i.imgur.com/E06FfNR.jpeg",
"https://i.imgur.com/bjVFOVS.jpeg",
"https://i.imgur.com/U9pfRnL.jpeg",
"https://i.imgur.com/bglQS36.jpeg",
"https://i.imgur.com/9Lmfo9b.jpeg",
"https://i.imgur.com/MeMnFPn.jpeg",
"https://i.imgur.com/2UTz8Xo.jpeg",
"https://i.imgur.com/EKOVcxj.jpeg",
"https://i.imgur.com/8viQv3u.jpeg",
"https://i.imgur.com/Ni4uZQN.jpeg",
"https://i.imgur.com/jHczj4Y.jpeg",
"https://i.imgur.com/nE6yiKc.jpeg",
"https://i.imgur.com/0nlAuXo.jpeg",
"https://i.imgur.com/PS8CSan.jpeg",
"https://i.imgur.com/nYhWvVy.jpeg",
"https://i.imgur.com/KUW7juY.jpeg",
"https://i.imgur.com/3lMrJns.jpeg",
"https://i.imgur.com/cvqMvpk.jpeg",
"https://i.imgur.com/aM8PwkZ.jpeg",
"https://i.imgur.com/tpeoS7C.jpeg",
"https://i.imgur.com/n3e8EWX.jpeg",
"https://i.imgur.com/1n2XRDP.jpeg",
"https://i.imgur.com/LKY5IDl.jpeg",
"https://i.imgur.com/gXo3SmR.jpeg",
"https://i.imgur.com/dFYZqDZ.jpeg",
"https://i.imgur.com/nkXVgEb.jpeg",
"https://i.imgur.com/GYYtSjq.jpeg",
"https://i.imgur.com/0mABbZK.jpeg",
"https://i.imgur.com/SpkuSjj.jpeg",
"https://i.imgur.com/NjUwX5d.jpeg",
"https://i.imgur.com/09L8FAr.jpeg",
"https://i.imgur.com/9erLQAO.jpeg",
"https://i.imgur.com/d34VJ9L.jpeg",
"https://i.imgur.com/RtAgLID.jpeg",
"https://i.imgur.com/YYDFpgi.jpeg",
"https://i.imgur.com/dt9G4d8.jpeg",
"https://i.imgur.com/RCIWvMA.jpeg",
"https://i.imgur.com/fEnnuYC.jpeg",
"https://i.imgur.com/LqFn7eg.jpeg",
"https://i.imgur.com/JR7r827.jpeg",
"https://i.imgur.com/ANJVquT.jpeg",
"https://i.imgur.com/EhPqOrZ.jpeg",
"https://i.imgur.com/ZpHSgv1.jpeg",
"https://i.imgur.com/bSjzr7S.jpeg",
"https://i.imgur.com/bgJknlq.jpeg",
"https://i.imgur.com/Aw8f2O2.jpeg",
"https://i.imgur.com/cjLmmtf.jpeg",
"https://i.imgur.com/Ue40RtY.jpeg",
"https://i.imgur.com/1INSdYh.jpeg",
"https://i.imgur.com/ptXWzAV.jpeg",
"https://i.imgur.com/SPFWOGq.jpeg",
"https://i.imgur.com/IGN4R0N.jpeg",
"https://i.imgur.com/T7ePEJe.jpeg",
"https://i.imgur.com/4cBXKW9.jpeg",
"https://i.imgur.com/cPhcwH7.jpeg",
"https://i.imgur.com/2xCnaDr.jpeg",
"https://i.imgur.com/wEGPOaX.jpeg",
"https://i.imgur.com/Oh4Tl4B.jpeg",
"https://i.imgur.com/dIlvYLT.jpeg",
"https://i.imgur.com/7dn6K5r.jpeg",
"https://i.imgur.com/HodOEqA.jpeg",
"https://i.imgur.com/sxgzk8M.jpeg",
"https://i.imgur.com/hL5bCIN.jpeg",
"https://i.imgur.com/kWUVNnZ.jpeg",
"https://i.imgur.com/WPKfEC8.jpeg",
"https://i.imgur.com/SVB6SaV.jpeg",
"https://i.imgur.com/uFgeWNs.jpeg",
"https://i.imgur.com/4f2OY5N.jpeg",
"https://i.imgur.com/ypknTTj.jpeg",
"https://i.imgur.com/x26OjQ0.jpeg",
"https://i.imgur.com/aWHi4Da.jpeg",
"https://i.imgur.com/TCW0dx0.jpeg",
"https://i.imgur.com/eBf4GVo.jpeg",
"https://i.imgur.com/LlcYUp1.jpeg",
"https://i.imgur.com/Ypxp8ue.jpeg",
"https://i.imgur.com/SNUCV40.jpeg",
"https://i.imgur.com/T2RVmGr.jpeg",
"https://i.imgur.com/DATDlnm.jpeg",
"https://i.imgur.com/4w4BKUc.jpeg",
"https://i.imgur.com/j04aL8h.jpeg",
"https://i.imgur.com/APGE1kg.jpeg",
"https://i.imgur.com/ImFkxPM.jpeg",
"https://i.imgur.com/iyk9MdM.jpeg",
"https://i.imgur.com/tjVTUh2.jpeg",
"https://i.imgur.com/xJlHhLm.jpeg",
"https://i.imgur.com/BPvPYf9.jpeg",
"https://i.imgur.com/GdabtPl.jpeg",
"https://i.imgur.com/S6m0ngr.jpeg",
"https://i.imgur.com/Y8yhG6K.jpeg",
"https://i.imgur.com/mp7dejJ.jpeg",
"https://i.imgur.com/iuWiQm4.jpeg",
"https://i.imgur.com/LyWCrUH.jpeg",
"https://i.imgur.com/1LcLmgS.jpeg",
"https://i.imgur.com/EAYJ0zK.jpeg",
"https://i.imgur.com/Q3W0VUM.jpeg",
"https://i.imgur.com/gr6wYCC.jpeg",
"https://i.imgur.com/7nut6rn.jpeg",
"https://i.imgur.com/WOHzwgY.jpeg",
"https://i.imgur.com/FeFGdmx.jpeg",
"https://i.imgur.com/n455I2i.jpeg",
"https://i.imgur.com/7mTkaWI.jpeg",
"https://i.imgur.com/6jAZGDy.jpeg",
"https://i.imgur.com/6ZxQiwi.jpeg",
"https://i.imgur.com/QywnxmO.jpeg",
"https://i.imgur.com/0ujJYEN.jpeg",
"https://i.imgur.com/QMvXJ7I.jpeg",
"https://i.imgur.com/C2Roj6q.jpeg",
"https://i.imgur.com/jcToIbz.jpeg",
"https://i.imgur.com/HLSownp.jpeg",
"https://i.imgur.com/hjsuAIU.jpeg",
"https://i.imgur.com/CCuVxSU.jpeg",
"https://i.imgur.com/g2aiG55.jpeg",
"https://i.imgur.com/RXhZyK8.jpeg",
"https://i.imgur.com/w82M8Mv.jpeg",
"https://i.imgur.com/St2KPh3.jpeg",
"https://i.imgur.com/RRlLRsW.jpeg",
"https://i.imgur.com/zODLAlx.jpeg",
"https://i.imgur.com/Fgz4TRS.jpeg",
"https://i.imgur.com/KiVldDd.jpeg",
"https://i.imgur.com/u5yzJrv.jpeg",
"https://i.imgur.com/5iVGRPn.jpeg",
"https://i.imgur.com/ioKTrMw.jpeg",
"https://i.imgur.com/xAc4GEF.jpeg",
"https://i.imgur.com/3RerMLO.jpeg",
"https://i.imgur.com/NopM0Y4.jpeg",
"https://i.imgur.com/k3Q194S.jpeg",
"https://i.imgur.com/2dzyYlg.jpeg",
"https://i.imgur.com/1pQxvvn.jpeg",
"https://i.imgur.com/UNZVYcp.jpeg",
"https://i.imgur.com/uKwcuoi.jpeg",
"https://i.imgur.com/ckftc6W.jpeg",
"https://i.imgur.com/YDkjaJc.jpeg",
"https://i.imgur.com/GybUB9R.jpeg",
"https://i.imgur.com/MAzpVEa.jpeg",
"https://i.imgur.com/xdNI3J1.jpeg",
"https://i.imgur.com/E9gCQPJ.jpeg",
"https://i.imgur.com/5fId1CP.jpeg",
"https://i.imgur.com/Uu8DkMO.jpeg",
"https://i.imgur.com/gmqdcTk.jpeg",
"https://i.imgur.com/8MU0CFW.jpeg",
"https://i.imgur.com/OaM6mfY.jpeg",
"https://i.imgur.com/htUQpqC.jpeg",
"https://i.imgur.com/t3xb4kq.jpeg",
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: " স্টাইল সাইট ব্যানার 😎🤏 ",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
