var mysterious = "Siegfried Sama";
const request = require("request");
const fs = require("fs")
const axios = require("axios")
module.exports.config = {
  name: "bob",
  version: "3.0.0",
  hasPermssion: 0,
  credits: `${mysterious}`,
  description: "girl to boy slap",
  commandCategory: "...",
  usages: "[tag]",
  cooldowns: 5,
};

module.exports.run = async({ api, event, Threads, global }) => {
  var link = [
"https://i.imgur.com/aACbQt7.gif",
"https://i.imgur.com/S03BGHA.gif",
"https://i.imgur.com/aqbdtz3.gif",
"https://i.imgur.com/Vs2Sufq.gif",
"https://i.imgur.com/h2sPP3n.gif",
"https://i.imgur.com/YRwonrn.gif",
"https://i.imgur.com/lR3oytE.gif",
"https://i.imgur.com/uLBUECf.gif",
"https://i.imgur.com/QwmTgOD.gif",
"https://i.imgur.com/IfDNkmG.gif",
"https://i.imgur.com/aRvIzEr.gif",
"https://i.imgur.com/WpWbZCA.gif",
"https://i.imgur.com/TR35cIV.gif",
"https://i.imgur.com/JJItF7i.gif",
"https://i.imgur.com/toDH7M4.gif",
"https://i.imgur.com/42asXxv.gif",
"https://i.imgur.com/gixNBLq.gif",
"https://i.imgur.com/JGoIB6R.gif",
"https://i.imgur.com/oOnPAGl.gif",
"https://i.imgur.com/KNIsb2k.gif",
"https://i.imgur.com/9PFeY21.gif",
"https://i.imgur.com/n91AuPc.gif",
"https://i.imgur.com/VzDWIrh.gif",
"https://i.imgur.com/oKWou1H.gif",
"https://i.imgur.com/1js6n1Q.gif",
"https://i.imgur.com/zE6L9yK.gif",
"https://i.imgur.com/EFvrvrU.gif",
"https://i.imgur.com/oKSOeYo.gif",
"https://i.imgur.com/8CMsK9Y.gif",
"https://i.imgur.com/YV2Pf4y.gif",
"https://i.imgur.com/XbKHBgL.gif",
"https://i.imgur.com/AYevHVo.gif",
"https://i.imgur.com/vJbhaP5.gif",
"https://i.imgur.com/gA8UBzA.gif",
"https://i.imgur.com/03vpcP5.gif",
"https://i.imgur.com/RKgmD5L.gif",
"https://i.imgur.com/VZrE8y9.gif",
"https://i.imgur.com/BZp1jWW.gif",
"https://i.imgur.com/0aEmu89.gif",
"https://i.imgur.com/4f0hwFG.gif",
"https://i.imgur.com/SgH40kP.gif",
"https://i.imgur.com/xWBhfDx.gif",
"https://i.imgur.com/3pZpmoS.gif",
"https://i.imgur.com/Acc4eQz.gif",
"https://i.imgur.com/PdJ2jn2.gif",
"https://i.imgur.com/pQJNggR.gif",
"https://i.imgur.com/y1DLnMK.gif",
"https://i.imgur.com/gaRmobq.gif",
"https://i.imgur.com/GKnCZiJ.gif",
"https://i.imgur.com/51kBEdb.gif",
"https://i.imgur.com/fwPdyN8.gif",
"https://i.imgur.com/xDsOVS8.gif",
"https://i.imgur.com/efRjpzL.gif",
"https://i.imgur.com/cQ7XpRs.gif",
"https://i.imgur.com/cZsLD4D.gif",
"https://i.imgur.com/tD2sYzn.gif",
"https://i.imgur.com/sb8lYGv.gif",
"https://i.imgur.com/rayk0El.gif",
"https://i.imgur.com/Goo4IEo.gif",
"https://i.imgur.com/ZtwWpDx.gif",
"https://i.imgur.com/1WF6VqG.gif",
"https://i.imgur.com/Peg232u.gif",
"https://i.imgur.com/lXPbsz3.gif",
"https://i.imgur.com/mkBD7DJ.gif",
"https://i.imgur.com/923npnJ.gif",
"https://i.imgur.com/Be61UHB.gif",
"https://i.imgur.com/cL43QfC.gif",
"https://i.imgur.com/VF5Sqj7.gif",
"https://i.imgur.com/4ijbpVL.gif",
"https://i.imgur.com/or7I1WV.gif",
"https://i.imgur.com/0wK1SyD.gif",
"https://i.imgur.com/AmlUlgO.gif",
"https://i.imgur.com/lv6k3x2.gif",
"https://i.imgur.com/8u1Vdp3.gif",
"https://i.imgur.com/PfSo21H.gif",
"https://i.imgur.com/iBg24Lj.gif",
"https://i.imgur.com/wgD9gSN.gif",
"https://i.imgur.com/tYCMeIR.gif",
"https://i.imgur.com/ivsCp7r.gif",
"https://i.imgur.com/EczX2HV.gif",
"https://i.imgur.com/c3q9A8T.gif",
"https://i.imgur.com/uN3yKO1.gif",
"https://i.imgur.com/WM4XA7D.gif",
"https://i.imgur.com/nGqVsDm.gif",
"https://i.imgur.com/uG1mPGb.gif",
"https://i.imgur.com/YVSWfDB.gif",
"https://i.imgur.com/OiEdHmH.gif",
"https://i.imgur.com/KbTlOYL.gif",
"https://i.imgur.com/WHoHa3x.gif",
"https://i.imgur.com/XusGzhQ.gif",
"https://i.imgur.com/Vzgz400.gif",
"https://i.imgur.com/dAalJSK.gif",
"https://i.imgur.com/4EM85cX.gif",
"https://i.imgur.com/8ZZNBEg.gif",
"https://i.imgur.com/cigi4vh.gif",
"https://i.imgur.com/LyTU4b0.gif",
"https://i.imgur.com/z9BEmua.gif",
"https://i.imgur.com/tqH4Vvh.gif",
"https://i.imgur.com/GJnmRJE.gif",
"https://i.imgur.com/D9RtS2I.gif",
"https://i.imgur.com/J5ZYzG8.gif",
"https://i.imgur.com/vpwRkF4.gif",
"https://i.imgur.com/qQ78mOc.gif",
"https://i.imgur.com/6a4CRdi.gif",
"https://i.imgur.com/6dCS2hB.gif",
"https://i.imgur.com/Yfphcjg.gif",
"https://i.imgur.com/4fzfif4.gif",
"https://i.imgur.com/GTx0Thn.gif",
"https://i.imgur.com/Kgq5Fq6.gif",
"https://i.imgur.com/XbhvwnE.gif",
"https://i.imgur.com/o2jpUJM.gif",
"https://i.imgur.com/B9x0KMu.gif",
"https://i.imgur.com/9plSOKl.gif",
"https://i.imgur.com/zW9ufQh.gif",
"https://i.imgur.com/kHen3tY.gif",
"https://i.imgur.com/8Gg6I3q.gif",
"https://i.imgur.com/ZaAZ1OW.gif",
"https://i.imgur.com/aS2NMWy.gif",
"https://i.imgur.com/IDPuBKv.gif",
"https://i.imgur.com/WDb0BpW.gif",
"https://i.imgur.com/CqtjPtm.gif",
"https://i.imgur.com/4IF1X7l.gif",
"https://i.imgur.com/2ugPjQZ.gif",
"https://i.imgur.com/dVbiy1E.gif",
"https://i.imgur.com/OP5maYG.gif",
"https://i.imgur.com/UeMCcLj.gif",
"https://i.imgur.com/Ki5uGiV.gif",
"https://i.imgur.com/E2uuFtO.gif",
"https://i.imgur.com/EGTLAlz.gif",
"https://i.imgur.com/vmhSh6S.gif",
"https://i.imgur.com/jSysO9h.gif",
"https://i.imgur.com/717lozo.gif",
"https://i.imgur.com/2GCpmKp.gif",
"https://i.imgur.com/ijErPwA.gif",
"https://i.imgur.com/yyQIqlI.gif",
"https://i.imgur.com/Q2s2FZI.gif",
"https://i.imgur.com/fkKKKQe.gif",
"https://i.imgur.com/IfmLP6T.gif",
"https://i.imgur.com/mKxBsxD.gif",
"https://i.imgur.com/DfRALfo.gif",
"https://i.imgur.com/CECJXTL.gif",
"https://i.imgur.com/TAgxKIi.gif",
"https://i.imgur.com/Kwqxc42.gif",
"https://i.imgur.com/v9K82wE.gif",
"https://i.imgur.com/O7OgDVa.gif",
"https://i.imgur.com/1j4CxjR.gif",
"https://i.imgur.com/hYnJWka.gif",
"https://i.imgur.com/wrgWMa2.gif",
"https://i.imgur.com/TLioP3O.gif",
"https://i.imgur.com/IDgLTZO.gif",

];
   var mention = Object.keys(event.mentions);
     let tag = event.mentions[mention].replace("@", "");
    if (!mention) return api.sendMessage("Mention 1 person that you want to f*** you ", threadID, messageID);
   var callback = () => api.sendMessage({body:`╭──────•◈•───────╮\n\n\n 🖕🖕 ${tag}` + `\n\n  এই দেখো , 😎 তোমাকে আমি এইভাবে খেলব🥵 🤏\n\n\n╰──────•◈•───────╯`,mentions: [{tag: tag,id: Object.keys(event.mentions)[0]}],attachment: fs.createReadStream(__dirname + "/cache/slap.gif")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/slap.gif"));  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/slap.gif")).on("close",() => callback());
              }
