const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "boypic",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/NymjC4m.jpeg",
"https://i.imgur.com/5dISm9D.jpeg",
"https://i.imgur.com/o39XV5J.jpeg",
"https://i.imgur.com/roj3rfJ.jpeg",
"https://i.imgur.com/66aS3xh.jpeg",
"https://i.imgur.com/gF958X0.jpeg",
"https://i.imgur.com/XPflmhj.jpeg",
"https://i.imgur.com/Orqad1I.jpeg",
"https://i.imgur.com/JUV1qJ1.jpeg",
"https://i.imgur.com/630sb9r.jpeg",
"https://i.imgur.com/elmvFju.jpeg",
"https://i.imgur.com/jt0yTgI.jpeg",
"https://i.imgur.com/XWkDYbP.jpeg",
"https://i.imgur.com/CZPt69J.jpeg",
"https://i.imgur.com/pcKE51o.jpeg",
"https://i.imgur.com/Uqka3uQ.jpeg",
"https://i.imgur.com/VvsX93F.jpeg",
"https://i.imgur.com/TUI13wU.jpeg",
"https://i.imgur.com/LNzw1f1.jpeg",
"https://i.imgur.com/LrloDhv.jpeg",
"https://i.imgur.com/uZjyuCB.jpeg",
"https://i.imgur.com/Iqn6p1T.jpeg",
"https://i.imgur.com/zeF13SF.jpeg",
"https://i.imgur.com/O2lxnG3.jpeg",
"https://i.imgur.com/10G2R2G.jpeg",
"https://i.imgur.com/Cb69hgT.jpeg",
"https://i.imgur.com/39NP3wu.jpeg",
"https://i.imgur.com/8Us8Vrw.jpeg",
"https://i.imgur.com/bFTcSiZ.jpeg",
"https://i.imgur.com/HIsOLr0.jpeg",
"https://i.imgur.com/eLttTi5.jpeg",
"https://i.imgur.com/CDxBA7b.jpeg",
"https://i.imgur.com/LYqtFXa.jpeg",
"https://i.imgur.com/ufYVjdK.jpeg",
"https://i.imgur.com/1G5CSAq.jpeg",
"https://i.imgur.com/pdJmGiN.jpeg",
"https://i.imgur.com/bHQMRdQ.jpeg",
"https://i.imgur.com/TfCC610.jpeg",
"https://i.imgur.com/cnDU32e.jpeg",
"https://i.imgur.com/baIgIcM.jpeg",
"https://i.imgur.com/RxTLTq8.jpeg",
"https://i.imgur.com/nIFSvXW.jpeg",
"https://i.imgur.com/5XX33cR.jpeg",
"https://i.imgur.com/iVDHbUz.jpeg",
"https://i.imgur.com/uuhPuZp.jpeg",
"https://i.imgur.com/D7sHpkz.jpeg",
"https://i.imgur.com/qFcakay.jpeg",
"https://i.imgur.com/ZsixV57.jpeg",
"https://i.imgur.com/t2MTm8r.jpeg",
"https://i.imgur.com/QLKSrh6.jpeg",
"https://i.imgur.com/0SFMIru.jpeg",
"https://i.imgur.com/6EQBdHO.jpeg",
"https://i.imgur.com/kZ6xI4M.jpeg",
"https://i.imgur.com/36V7Om4.jpeg",
"https://i.imgur.com/Z634ml5.jpeg",
"https://i.imgur.com/0pDzr0n.jpeg",
"https://i.imgur.com/pJmq1V4.jpeg",
"https://i.imgur.com/c5vSqrc.jpeg",
"https://i.imgur.com/82P4uwA.jpeg",
"https://i.imgur.com/vcpmr98.jpeg",
"https://i.imgur.com/5foHzQY.jpeg",
"https://i.imgur.com/T5P3noJ.jpeg",
"https://i.imgur.com/ZHzKLTJ.jpeg",
"https://i.imgur.com/8jlFqJU.jpeg",
"https://i.imgur.com/fglo5dZ.jpeg",
"https://i.imgur.com/hY3GRez.jpeg",
"https://i.imgur.com/i359Ph0.jpeg",
"https://i.imgur.com/ruK2nb1.jpeg",
"https://i.imgur.com/Q649SfG.jpeg",
"https://i.imgur.com/IiUccAk.jpeg",
"https://i.imgur.com/Fvt4hZX.jpeg",
"https://i.imgur.com/IFlLu1P.jpeg",
"https://i.imgur.com/I1eYK8k.jpeg",
"https://i.imgur.com/LTudr4Z.jpeg",
"https://i.imgur.com/X9VtIKr.jpeg",
"https://i.imgur.com/PIeSM9u.jpeg",
"https://i.imgur.com/6gvxmmR.jpeg",
"https://i.imgur.com/3SmNOOn.jpeg",
"https://i.imgur.com/AcHLOkS.jpeg",
"https://i.imgur.com/lN1LZ5P.jpeg",
"https://i.imgur.com/hynND5g.jpeg",
"https://i.imgur.com/v0xE7KC.jpeg",
"https://i.imgur.com/yhgFUP9.jpeg",
"https://i.imgur.com/7ocoB3B.jpeg",
"https://i.imgur.com/JD6P6zT.jpeg",
"https://i.imgur.com/L1AOCwx.jpeg",
"https://i.imgur.com/mweQ3w0.jpeg",
"https://i.imgur.com/6mg0jFG.jpeg",
"https://i.imgur.com/RN6DfXx.jpeg",
"https://i.imgur.com/po4Tvwx.jpeg",
"https://i.imgur.com/KX7PUbc.jpeg",
"https://i.imgur.com/VP0ISG7.jpeg",
"https://i.imgur.com/nJ9LFfL.jpeg",
"https://i.imgur.com/vgYM366.jpeg",
"https://i.imgur.com/ObmTz4b.jpeg",
"https://i.imgur.com/k4LvtI0.jpeg",
"https://i.imgur.com/5Zbdxg9.jpeg",
"https://i.imgur.com/yHMV2Z2.jpeg",
"https://i.imgur.com/FBTVy1b.jpeg",
"https://i.imgur.com/tjsvJpJ.jpeg",
"https://i.imgur.com/mDr0ziW.jpeg",
"https://i.imgur.com/PW0qiam.jpeg",
"https://i.imgur.com/lUIgtLC.jpeg",
"https://i.imgur.com/KmRTPgb.jpeg",
"https://i.imgur.com/9zuVF2U.jpeg",
"https://i.imgur.com/6FsslPS.jpeg",
"https://i.imgur.com/JN4Iut0.jpeg",
"https://i.imgur.com/mopwe8N.jpeg",
"https://i.imgur.com/aVFPPEy.jpeg",
"https://i.imgur.com/qgdp49z.jpeg",
"https://i.imgur.com/OQ38gxR.jpeg",
"https://i.imgur.com/nBCAR1z.jpeg",
"https://i.imgur.com/x3RmxqP.jpeg",
"https://i.imgur.com/dUTBmec.jpeg",
"https://i.imgur.com/UmSwKCq.jpeg",
"https://i.imgur.com/sVSlJyx.jpeg",
"https://i.imgur.com/Y10GvpR.jpeg",
"https://i.imgur.com/TYU7gpN.jpeg",
"https://i.imgur.com/nAxxbAL.jpeg",
"https://i.imgur.com/Uca6ooJ.jpeg",
"https://i.imgur.com/jqUdqyD.jpeg",
"https://i.imgur.com/5KoHLFP.jpeg",
"https://i.imgur.com/Mt4Lhfb.jpeg",
"https://i.imgur.com/mULE80M.jpeg",
"https://i.imgur.com/KHlY66f.jpeg",
"https://i.imgur.com/0YduiMk.jpeg",
"https://i.imgur.com/cmmq2o9.jpeg",
"https://i.imgur.com/LTaDY1I.jpeg",
"https://i.imgur.com/4JwjTBG.jpeg",
"https://i.imgur.com/HXdAbaO.jpeg",
"https://i.imgur.com/87dEJtk.jpeg",
"https://i.imgur.com/FwOhhcs.jpeg",
"https://i.imgur.com/eY2ieNf.jpeg",
"https://i.imgur.com/xOYqgVA.jpeg",
"https://i.imgur.com/mc5rBeM.jpeg",
"https://i.imgur.com/PfEl0NW.jpeg",
"https://i.imgur.com/mu3yHdP.jpeg",
"https://i.imgur.com/hBBazH7.jpeg",
"https://i.imgur.com/TxDHEhj.jpeg",
"https://i.imgur.com/EWgbEkp.jpeg",
"https://i.imgur.com/uAU9GLM.jpeg",
"https://i.imgur.com/2MulPXD.jpeg",
"https://i.imgur.com/swxvWcG.jpeg",
"https://i.imgur.com/kN8oL2J.jpeg",
"https://i.imgur.com/unVEvS6.jpeg",
"https://i.imgur.com/jmJdRDw.jpeg",
"https://i.imgur.com/k9w8lF4.jpeg",
"https://i.imgur.com/RuIkLPD.jpeg",
"https://i.imgur.com/W6uWiqz.jpeg",
"https://i.imgur.com/xsh8zEL.jpeg",
"https://i.imgur.com/fQa6nAG.jpeg",
"https://i.imgur.com/9QYYaMu.jpeg",
"https://i.imgur.com/NyGAvFF.jpeg",
"https://i.imgur.com/NxoXrhi.jpeg",
"https://i.imgur.com/7eIK6O5.jpeg",
"https://i.imgur.com/3qhxv8C.jpeg",
"https://i.imgur.com/RwIymqF.jpeg",
"https://i.imgur.com/JtAc8Bf.jpeg",
"https://i.imgur.com/h0QxRdF.jpeg",
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "Facebook Boy Profile 🤌🙂",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
