const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "boypicv2",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/itrIOSu.jpeg",
"https://i.imgur.com/7axQZGX.jpeg",
"https://i.imgur.com/2t8YEY7.jpeg",
"https://i.imgur.com/bgWqsIr.jpeg",
"https://i.imgur.com/vmr9jAR.jpeg",
"https://i.imgur.com/uvXsdVu.jpeg",
"https://i.imgur.com/UAmU5Je.jpeg",
"https://i.imgur.com/T3dwHSg.jpeg",
"https://i.imgur.com/rL40Q8g.jpeg",
"https://i.imgur.com/a2YMp2e.jpeg",
"https://i.imgur.com/hquE9lw.jpeg",
"https://i.imgur.com/bHRU1Sl.jpeg",
"https://i.imgur.com/Gve3aah.jpeg",
"https://i.imgur.com/j7BK6rB.jpeg",
"https://i.imgur.com/KYa9Lxd.jpeg",
"https://i.imgur.com/qWodREW.jpeg",
"https://i.imgur.com/Bw8HVeG.jpeg",
"https://i.imgur.com/awyw6Os.jpeg",
"https://i.imgur.com/vKT3z2u.jpeg",
"https://i.imgur.com/kK13CWd.jpeg",
"https://i.imgur.com/P4e8HCe.jpeg",
"https://i.imgur.com/cvxnsAm.jpeg",
"https://i.imgur.com/0NbAvCG.jpeg",
"https://i.imgur.com/diZPIc1.jpeg",
"https://i.imgur.com/uMaP9iL.jpeg",
"https://i.imgur.com/meXDEeK.jpeg",
"https://i.imgur.com/OhdPjXv.jpeg",
"https://i.imgur.com/KxwfVlB.jpeg",
"https://i.imgur.com/GV54cNG.jpeg",
"https://i.imgur.com/H14ie9d.jpeg",
"https://i.imgur.com/fFhTPvc.jpeg",
"https://i.imgur.com/A0jchUz.jpeg",
"https://i.imgur.com/BsX9Ook.jpeg",
"https://i.imgur.com/K7Bd1xF.jpeg",
"https://i.imgur.com/FP2sK2J.jpeg",
"https://i.imgur.com/ydniGoI.jpeg",
"https://i.imgur.com/06c5eHW.jpeg",
"https://i.imgur.com/FS6s28H.jpeg",
"https://i.imgur.com/tCX6KVm.jpeg",
"https://i.imgur.com/XZoahCN.jpeg",
"https://i.imgur.com/JhzpL6P.jpeg",
"https://i.imgur.com/L4vkHPL.jpeg",
"https://i.imgur.com/UyUZQyW.jpeg",
"https://i.imgur.com/BHjqVtf.jpeg",
"https://i.imgur.com/sP2daba.jpeg",
"https://i.imgur.com/7kygWPx.jpeg",
"https://i.imgur.com/TgcYyIu.jpeg",
"https://i.imgur.com/JqrQlrK.jpeg",
"https://i.imgur.com/A1K4zb5.jpeg",
"https://i.imgur.com/ymYlFXu.jpeg",
"https://i.imgur.com/ZApuc29.jpeg",
"https://i.imgur.com/TSWynVE.jpeg",
"https://i.imgur.com/xt9wYgi.jpeg",
"https://i.imgur.com/uyV2fcf.jpeg",
"https://i.imgur.com/iA4VNa5.jpeg",
"https://i.imgur.com/QqCn9TF.jpeg",
"https://i.imgur.com/0vS1ShD.jpeg",
"https://i.imgur.com/oKsHLEQ.jpeg",
"https://i.imgur.com/xj1pdY2.jpeg",
"https://i.imgur.com/na7QGjx.jpeg",
"https://i.imgur.com/Npe3rG7.jpeg",
"https://i.imgur.com/ZedpIMN.jpeg",
"https://i.imgur.com/bGzK7BS.jpeg",
"https://i.imgur.com/c6QG7dW.jpeg",
"https://i.imgur.com/FSeQthP.jpeg",
"https://i.imgur.com/HixNsxd.jpeg",
"https://i.imgur.com/hCvNA8K.jpeg",
"https://i.imgur.com/r0qpNNN.jpeg",
"https://i.imgur.com/vwuUKzq.jpeg",
"https://i.imgur.com/LjfTZrh.jpeg",
"https://i.imgur.com/mSgfCn1.jpeg",
"https://i.imgur.com/bMcwtwm.jpeg",
"https://i.imgur.com/jhJV5Nw.jpeg",
"https://i.imgur.com/YIzgdRM.jpeg",
"https://i.imgur.com/zcNhzVM.jpeg",
"https://i.imgur.com/O3PS2WD.jpeg",
"https://i.imgur.com/BBWTYwi.jpeg",
"https://i.imgur.com/bZm89jm.jpeg",
"https://i.imgur.com/AyO8XfM.jpeg",
"https://i.imgur.com/lipsgIy.jpeg",
"https://i.imgur.com/7SyPpJF.jpeg",
"https://i.imgur.com/hT8e4cv.jpeg",
"https://i.imgur.com/tOmkARp.jpeg",
"https://i.imgur.com/5jevOhl.jpeg",
"https://i.imgur.com/h7PkDnh.jpeg",
"https://i.imgur.com/BLRVoGi.jpeg",
"https://i.imgur.com/Vhzpih1.jpeg",
"https://i.imgur.com/aOJOMWH.jpeg",
"https://i.imgur.com/EwUSf7M.jpeg",
"https://i.imgur.com/Sp4p39S.jpeg",
"https://i.imgur.com/6UF2WZD.jpeg",
"https://i.imgur.com/LoXT60g.jpeg",
"https://i.imgur.com/SMNnPv7.jpeg",
"https://i.imgur.com/XONmrBY.jpeg",
"https://i.imgur.com/4RfgvNn.jpeg",
"https://i.imgur.com/IMZzh9c.jpeg",
"https://i.imgur.com/Mzh5q6Z.jpeg",
"https://i.imgur.com/iIZfS4b.jpeg",
"https://i.imgur.com/TUNfl7J.jpeg",
"https://i.imgur.com/WnNSCaG.jpeg",
"https://i.imgur.com/3azDFNK.jpeg",
"https://i.imgur.com/MyH2u46.jpeg",
"https://i.imgur.com/SKYpWJG.jpeg",
"https://i.imgur.com/E1ac7WP.jpeg",
"https://i.imgur.com/zutuyYz.jpeg",
"https://i.imgur.com/gKhvUl2.jpeg",
"https://i.imgur.com/CWi4dVK.jpeg",
"https://i.imgur.com/ABzEoqj.jpeg",
"https://i.imgur.com/XpQpqtF.jpeg",
"https://i.imgur.com/i8PXmN1.jpeg",
"https://i.imgur.com/cYgXrYb.jpeg",
"https://i.imgur.com/fF1ZXFB.jpeg",
"https://i.imgur.com/kGe4OF6.jpeg",
"https://i.imgur.com/6fsN4s6.jpeg",
"https://i.imgur.com/sqwXqWX.jpeg",
"https://i.imgur.com/vl6SrSO.jpeg",
"https://i.imgur.com/8MHPdmv.jpeg",
"https://i.imgur.com/4ygaqFg.jpeg",
"https://i.imgur.com/oquC377.jpeg",
"https://i.imgur.com/pReyBP9.jpeg",
"https://i.imgur.com/TGuFgXf.jpeg",
"https://i.imgur.com/TCl4dRC.jpeg",
"https://i.imgur.com/xKx6efu.jpeg",
"https://i.imgur.com/9Fqv3Zw.jpeg",
"https://i.imgur.com/7m43eKD.jpeg",
"https://i.imgur.com/aPyRo38.jpeg",
"https://i.imgur.com/V0wYIuD.jpeg",
"https://i.imgur.com/9Gcyd9K.jpeg",
"https://i.imgur.com/sP2Ggxc.jpeg",
"https://i.imgur.com/0wo7WMo.jpeg",
"https://i.imgur.com/7klUb5K.jpeg",
"https://i.imgur.com/l4qsPvc.jpeg",
"https://i.imgur.com/br0c99U.jpeg",
"https://i.imgur.com/Aqqiv33.jpeg",
"https://i.imgur.com/zaYa7sX.jpeg",
"https://i.imgur.com/waIXhnm.jpeg",
"https://i.imgur.com/pNhVd6M.jpeg",
"https://i.imgur.com/2ELcbTF.jpeg",
"https://i.imgur.com/7hRITzA.jpeg",
"https://i.imgur.com/JNMuBOE.jpeg",
"https://i.imgur.com/XrgQfyz.jpeg",
"https://i.imgur.com/7lqu9Aq.jpeg",
"https://i.imgur.com/ATy46Qs.jpeg",
"https://i.imgur.com/9K1pWZt.jpeg",
"https://i.imgur.com/N4M6CYh.jpeg",
"https://i.imgur.com/gTLzJGL.jpeg",
"https://i.imgur.com/9LBsup8.jpeg",
"https://i.imgur.com/A6dcZT6.jpeg",
"https://i.imgur.com/WwdFRif.jpeg",
"https://i.imgur.com/gEhFaIt.jpeg",
"https://i.imgur.com/JOqeQ3s.jpeg",
"https://i.imgur.com/knYQD4H.jpeg",
"https://i.imgur.com/qPimQdz.jpeg",
"https://i.imgur.com/mTmREqv.jpeg",
"https://i.imgur.com/btUnt94.jpeg",
"https://i.imgur.com/lTuKZlh.jpeg",
"https://i.imgur.com/cVJEF2E.jpeg",
"https://i.imgur.com/O9CT2Yy.jpeg",
"https://i.imgur.com/yro54nb.jpeg",
"https://i.imgur.com/ciKL4fR.jpeg",
"https://i.imgur.com/tYcn1dE.jpeg",
"https://i.imgur.com/CysOMSQ.jpeg",
"https://i.imgur.com/8eVj1C4.jpeg",
"https://i.imgur.com/ymIuH1N.jpeg",
"https://i.imgur.com/i3Ely9s.jpeg",
"https://i.imgur.com/TZfsuo3.jpeg",
"https://i.imgur.com/QjHmVQj.jpeg",
"https://i.imgur.com/Sxsaroo.jpeg",
"https://i.imgur.com/LCjnmBK.jpeg",
"https://i.imgur.com/m7lLhbj.jpeg",
"https://i.imgur.com/MiHPlfy.jpeg",
"https://i.imgur.com/hFQgaA9.jpeg",
"https://i.imgur.com/fIYNDpz.jpeg",
"https://i.imgur.com/MNiRy9A.jpeg",
"https://i.imgur.com/AN0jRBp.jpeg",
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "Facebook Boy Profile 🤌🙂 V2 ",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
