const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "sadiya",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [  "https://i.imgur.com/Ou4IJYV.jpeg",
"https://i.imgur.com/BStnCDy.jpeg",
"https://i.imgur.com/t2qWMKt.jpeg",
"https://i.imgur.com/bpOEMP9.jpeg",
"https://i.imgur.com/59GbC4R.jpeg",
"https://i.imgur.com/58oOCfV.jpeg",
"https://i.imgur.com/9TTzx0l.jpeg",
"https://i.imgur.com/kZeibBl.jpeg",
"https://i.imgur.com/TNhTJ8m.jpeg",
"https://i.imgur.com/fZUSPUl.jpeg",
"https://i.imgur.com/pf2ZLZq.jpeg",
"https://i.imgur.com/5UASt2O.jpeg",
"https://i.imgur.com/58X5pTj.jpeg",
"https://i.imgur.com/8CPIHn1.jpeg",
"https://i.imgur.com/B5qJE29.jpeg",
"https://i.imgur.com/puhPGE8.jpeg",
"https://i.imgur.com/4UYVhQN.jpeg",
"https://i.imgur.com/wAoOE8E.jpeg",
"https://i.imgur.com/F0EFCZl.jpeg",
"https://i.imgur.com/0Jh5ClS.jpeg",
"https://i.imgur.com/ObVvTA4.jpeg",
"https://i.imgur.com/z4GbW7m.jpeg",
"https://i.imgur.com/Ztg3tmx.jpeg",
"https://i.imgur.com/iUbE0Q5.jpeg",
"https://i.imgur.com/QYIDELe.jpeg",
"https://i.imgur.com/G3ti4wk.jpeg",
"https://i.imgur.com/mDPeEcG.jpeg",
"https://i.imgur.com/VtcybRj.jpeg",
"https://i.imgur.com/cEWL4py.jpeg",
"https://i.imgur.com/pGFmVPk.jpeg",
"https://i.imgur.com/oGL9W6z.jpeg",
"https://i.imgur.com/i7JWUsO.jpeg",
"https://i.imgur.com/vZs1PJW.jpeg",
"https://i.imgur.com/YSRZYoc.jpeg",
"https://i.imgur.com/mOzIKpm.jpeg",
"https://i.imgur.com/Nepxbg5.jpeg",
"https://i.imgur.com/jlTuFJV.jpeg",
"https://i.imgur.com/vpXpB4S.jpeg",
"https://i.imgur.com/G3mSTcw.jpeg",
"https://i.imgur.com/Yn0OLXs.jpeg",
"https://i.imgur.com/UFGjU1o.jpeg",
"https://i.imgur.com/gwKBZu2.jpeg",
"https://i.imgur.com/Utg59zN.jpeg",
"https://i.imgur.com/0dX6eXL.jpeg",
"https://i.imgur.com/adOI9gL.jpeg",
"https://i.imgur.com/wJv5Z2a.jpeg",
"https://i.imgur.com/eznbBZE.jpeg",
"https://i.imgur.com/Z7CFzyD.jpeg",
"https://i.imgur.com/t3OrW3u.jpeg",
"https://i.imgur.com/LPagcaL.jpeg",
"https://i.imgur.com/4bvfJg0.jpeg",
"https://i.imgur.com/jMKdjwU.jpeg",
"https://i.imgur.com/vfFrCHk.jpeg",
"https://i.imgur.com/3bwJguO.jpeg",
"https://i.imgur.com/ZNJTDcZ.jpeg",
"https://i.imgur.com/lN4mGU3.jpeg",
"https://i.imgur.com/DCZ7Zry.jpeg",
"https://i.imgur.com/2YnWiiq.jpeg",
"https://i.imgur.com/CMEpeDQ.jpeg",
"https://i.imgur.com/3l521OS.jpeg",
"https://i.imgur.com/eoZrgGb.jpeg",
"https://i.imgur.com/19CXcgT.jpeg",
"https://i.imgur.com/Sa57TJx.jpeg",
"https://i.imgur.com/RgriFLW.jpeg",
"https://i.imgur.com/b8nXLqf.jpeg",
"https://i.imgur.com/DAaDX86.jpeg",
"https://i.imgur.com/bKMLwXm.jpeg",
"https://i.imgur.com/euYdgEe.jpeg",
"https://i.imgur.com/v7XrH8L.jpeg",
"https://i.imgur.com/UV0RT3m.jpeg",
"https://i.imgur.com/sWFZTqJ.jpeg",
"https://i.imgur.com/fweRBl3.jpeg",
"https://i.imgur.com/4NjLoj0.jpeg",
"https://i.imgur.com/KwplkZJ.jpeg",
"https://i.imgur.com/JMYaGxD.jpeg",
"https://i.imgur.com/rAvt0Rv.jpeg",
"https://i.imgur.com/tJrHQuT.jpeg",
"https://i.imgur.com/zrf3Sla.jpeg",
"https://i.imgur.com/J0FSPbu.jpeg",
"https://i.imgur.com/fkFN4Xy.jpeg",
"https://i.imgur.com/DOCCr8U.jpeg",
"https://i.imgur.com/vSpLpYE.jpeg",
"https://i.imgur.com/7Mt8CsY.jpeg",
"https://i.imgur.com/OTmPyHN.jpeg",
"https://i.imgur.com/AfQkGRA.jpeg",
"https://i.imgur.com/k69NhPE.jpeg",
"https://i.imgur.com/957JJ5s.jpeg",
"https://i.imgur.com/YI4poQQ.jpeg",
"https://i.imgur.com/T2F1AO0.jpeg",
"https://i.imgur.com/ETPNsNs.jpeg",
"https://i.imgur.com/ODNzu7R.jpeg",
"https://i.imgur.com/vH3z11H.jpeg",
"https://i.imgur.com/f3u1ngH.jpeg",
"https://i.imgur.com/8cAaapk.jpeg",
"https://i.imgur.com/L2FZkOG.jpeg",
"https://i.imgur.com/oFUx7av.jpeg",
"https://i.imgur.com/mgP3j5T.jpeg",
"https://i.imgur.com/NPGrBvs.jpeg",
"https://i.imgur.com/1mk8RBg.jpeg",
"https://i.imgur.com/TlfrdxY.jpeg",
"https://i.imgur.com/D0hBfb0.jpeg",
"https://i.imgur.com/W1TWAld.jpeg",
"https://i.imgur.com/Wxdz59S.jpeg",
"https://i.imgur.com/Hti7i2f.jpeg",
"https://i.imgur.com/VfaCbpQ.jpeg",
"https://i.imgur.com/maFEp5q.jpeg",
"https://i.imgur.com/DPdFmK9.jpeg",
"https://i.imgur.com/EKWiDNo.jpeg",
"https://i.imgur.com/5l3L3oH.jpeg",
"https://i.imgur.com/vTWqB6c.jpeg",
"https://i.imgur.com/1j9A6pG.jpeg",
"https://i.imgur.com/MCkSN4a.jpeg",
"https://i.imgur.com/b0x91YA.jpeg",
"https://i.imgur.com/EXIbioT.jpeg",
"https://i.imgur.com/vFu3gt1.jpeg",
"https://i.imgur.com/zKq28Lz.jpeg",
"https://i.imgur.com/JzWmDiN.jpeg",
"https://i.imgur.com/hCnBWC1.jpeg",
"https://i.imgur.com/4uYcWpd.jpeg",
"https://i.imgur.com/uGBtKpX.jpeg",
"https://i.imgur.com/pOaiqPr.jpeg",
"https://i.imgur.com/HjqZ3V2.jpeg",
"https://i.imgur.com/EOZ1z2M.jpeg",
"https://i.imgur.com/Wa8s7Bo.jpeg",
"https://i.imgur.com/lpv0Oqv.jpeg",
"https://i.imgur.com/04bVoh8.jpeg",
"https://i.imgur.com/pfKfyvw.jpeg",
"https://i.imgur.com/grsRews.jpeg",
"https://i.imgur.com/JoLtAvS.jpeg",
"https://i.imgur.com/A6Hjlq4.jpeg",
"https://i.imgur.com/MCSdZN2.jpeg",
"https://i.imgur.com/s9Snke7.jpeg",
"https://i.imgur.com/i5cICC3.jpeg",
"https://i.imgur.com/xxeZMFI.jpeg",
"https://i.imgur.com/D5TyQ6o.jpeg",
"https://i.imgur.com/Shw9OYM.jpeg",
"https://i.imgur.com/baAAkE7.jpeg",
"https://i.imgur.com/rIALeLN.jpeg",
"https://i.imgur.com/0eaiAUH.jpeg",
"https://i.imgur.com/mfq5iXP.jpeg",
"https://i.imgur.com/48CIx8C.jpeg",
"https://i.imgur.com/aEvPU6m.jpeg",
"https://i.imgur.com/967mAAF.jpeg",
"https://i.imgur.com/eu1G1rE.jpeg",
"https://i.imgur.com/IkE0I3W.jpeg",
"https://i.imgur.com/lg5gMn2.jpeg",
"https://i.imgur.com/4LWtDNC.jpeg",
"https://i.imgur.com/xYBXv0X.jpeg",
"https://i.imgur.com/cxh58ul.jpeg",
"https://i.imgur.com/ALLiPdV.jpeg",
"https://i.imgur.com/lcDubTj.jpeg",
"https://i.imgur.com/7pTB5p5.jpeg",
"https://i.imgur.com/K28bpmC.jpeg",
"https://i.imgur.com/oe7hfGM.jpeg",
"https://i.imgur.com/aY8JPER.jpeg",
"https://i.imgur.com/5khh59g.jpeg",
"https://i.imgur.com/EBIl1p4.jpeg",
"https://i.imgur.com/cNy14w9.jpeg",
"https://i.imgur.com/pPC0tFG.jpeg",
"https://i.imgur.com/w5LOstH.jpeg",
"https://i.imgur.com/9ZkfjKh.jpeg",
"https://i.imgur.com/3vAJ3i1.jpeg",
"https://i.imgur.com/ETYL5cU.jpeg",
"https://i.imgur.com/OAAiGmF.jpeg",
"https://i.imgur.com/sUg1K3l.jpeg",
"https://i.imgur.com/RCCkmZ0.jpeg",
"https://i.imgur.com/r4agpTf.jpeg",
"https://i.imgur.com/F8VSclO.jpeg",
"https://i.imgur.com/DxcqrOZ.jpeg",
"https://i.imgur.com/w6V5IBq.jpeg",
"https://i.imgur.com/bayQSZg.jpeg",
"https://i.imgur.com/fE5rDJ6.jpeg",
"https://i.imgur.com/JwnVZu6.jpeg",
"https://i.imgur.com/An2uPyd.jpeg",
"https://i.imgur.com/2NUlHk9.jpeg",
"https://i.imgur.com/YAgvGlm.jpeg",
"https://i.imgur.com/onDC9WM.jpeg",
"https://i.imgur.com/15WQ5SB.jpeg",
"https://i.imgur.com/3DVKzYb.jpeg",
"https://i.imgur.com/ItklyZ7.jpeg",
"https://i.imgur.com/UtJva9Y.jpeg",
"https://i.imgur.com/6W2aMfy.jpeg",
"https://i.imgur.com/Lv0O6Qx.jpeg",
"https://i.imgur.com/Ps5g7xn.jpeg",
"https://i.imgur.com/enuT4aE.jpeg",
"https://i.imgur.com/niEmhS7.jpeg",
"https://i.imgur.com/quZ6CK7.jpeg",
"https://i.imgur.com/rfx1M42.jpeg",
"https://i.imgur.com/aR8xKYp.jpeg",
"https://i.imgur.com/DKwFlGu.jpeg",
"https://i.imgur.com/Y80cDHD.jpeg",
"https://i.imgur.com/ghewnZz.jpeg",
"https://i.imgur.com/ZxXT7QP.jpeg",
"https://i.imgur.com/3dJJTGM.jpeg",
"https://i.imgur.com/0tQonq5.jpeg",
"https://i.imgur.com/uBcj2yR.jpeg",
"https://i.imgur.com/J51Kg2y.jpeg",
"https://i.imgur.com/igQlZs9.jpeg",
"https://i.imgur.com/rfWZGfI.jpeg",
"https://i.imgur.com/xEYVAAR.jpeg",
"https://i.imgur.com/dZD0YtK.jpeg",
"https://i.imgur.com/NbCji7U.jpeg",
"https://i.imgur.com/VDL8zT5.jpeg",
"https://i.imgur.com/XqjiGr1.jpeg",
"https://i.imgur.com/jIlEorz.jpeg",
"https://i.imgur.com/nvOXotS.jpeg",
"https://i.imgur.com/4EfPcMF.jpeg",
"https://i.imgur.com/LGRs2Bd.jpeg",
"https://i.imgur.com/AtreWtj.jpeg",
"https://i.imgur.com/7DMMqYL.jpeg",
"https://i.imgur.com/5r4H20P.jpeg",
"https://i.imgur.com/sPodval.jpeg",
"https://i.imgur.com/nXRvWH2.jpeg",
"https://i.imgur.com/YIZoEnO.jpeg",
"https://i.imgur.com/AbsNB8t.jpeg",
"https://i.imgur.com/Rb1JI2r.jpeg",
"https://i.imgur.com/Q3UNetK.jpeg",
"https://i.imgur.com/MqXLsRu.jpeg",
"https://i.imgur.com/xVF7Dl6.jpeg",
"https://i.imgur.com/qz1BofH.jpeg",
"https://i.imgur.com/niuqaYP.jpeg",
"https://i.imgur.com/jkj2DGh.jpeg",
"https://i.imgur.com/MNZ0KpY.jpeg",
"https://i.imgur.com/HFnFtWq.jpeg",
"https://i.imgur.com/986kT3G.jpeg",
"https://i.imgur.com/hzYZkfH.jpeg",
"https://i.imgur.com/DTEu07x.jpeg",
"https://i.imgur.com/Q4HJFth.jpeg",
"https://i.imgur.com/Kh0XywI.jpeg",
"https://i.imgur.com/ZNoWNex.jpeg",
"https://i.imgur.com/tkq0t5G.jpeg",
"https://i.imgur.com/Cbx7GAD.jpeg",
"https://i.imgur.com/5qccp7p.jpeg",
"https://i.imgur.com/6p6cuyI.jpeg",
"https://i.imgur.com/37RJxuT.jpeg"
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "😒🤭😸😸😸😆",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
